language: node_js
notifications:
  email: false
deploy:
  provider: npm
  email: pollet.kevin@gmail.com
  api_key:
    secure: WEjlxZoxRPEdTiCx4MdQ0wd15mIKPVKUZH0N4NGHem9EqS8KzdsfHjxs5L0hP4D1NHIj7uC9ct/iRvuXbsRGa5AofPKaKVd4dfDUHrFNPJuEGjPPifH8J4nO5woOtmgqqnqw9OHLxGS+Q8NVaXem/lf+HSE5QMxdb2mSTug4da6XVaRAKn4/+hJl0+jtmAmt4fPeOYsE8FdRVxUte9DjJ7xGUgP6vFHl1zgN3QeYMUEQoFsga+UPh6lSnOtjKJcPCYjeAHCaDdG4TkCQSPMgmtvOJVZuyoNnqFYBycvLaHyQRHfGgrnkYIl43XzCnqyoV9nIQ1s6JlSu0Vo7NmNpITaEuKHPXr+/dwn6ZocGxoU7RU53AnA/qrKDfXRx36LtvXMpKS11xqSexAbUYDxrOkqob5EtrBbCvKxty5bgmqt60lbkEDtIupzw2jZoPExH90b8u4IldszT94gRFkz2mZvvgwCiB9HfqCQCBLQbldGaG1EvAJiR3z/WOFt8NqgbcB0ezqq5sXWG6NyIEUx9ZvQRHq9SS0ezHWwevYcRcflDR7HW8Hr0t3BPgsbfeGDtYN7UDhLD0+QneHtnn4yv0XDQEAMLpXYE4fSqTsqGsskxXEQnDvs+euAbhls3Knj/LqH1oxHm22zAhT1WATc3p0zGyUHApUhuGP7kRmuCxgs=
  tag: latest
  on:
    tags: true
